storage:
  storage_path: /qdrant/storage
  snapshots_path: /qdrant/snapshots
  on_disk_payload: true

  optimizers:
    deleted_threshold: 0.2
    indexing_threshold: 10000
    memmap_threshold: 20000
    max_optimization_threads: 1

service:
  http_port: 6333
  grpc_port: 6334
